### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by choiks14** [ConnectyCube/android-messenger-app#19]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.connectycube.messenger, PID: 17898
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.connectycube.messenger.ChatDialogActivity$subscribeUi$$inlined$observe$1.onChanged(LiveData.kt:56)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.Transformations$1.onChanged(Transformations.java:76)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.connectycube.messenger.viewmodels.ChatDialogListViewModel$getChats$1.onChanged(ChatDialogListViewModel.kt:33)
        at com.connectycube.messenger.viewmodels.ChatDialogListViewModel$getChats$1.onChanged(ChatDialogListViewModel.kt:13)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.connectycube.messenger.vo.NetworkBoundResource.setValue(NetworkBoundResource.kt:56)
        at com.connectycube.messenger.vo.NetworkBoundResource.access$setValue(NetworkBoundResource.kt:21)
        at com.connectycube.messenger.vo.NetworkBoundResource$1$1$1.onChanged(NetworkBoundResource.kt:46)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:144)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:443)
        at androidx.lifecycle.LiveData.observeForever(LiveData.java:232)
        at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
        at androidx.lifecycle.MediatorLiveData.addSource(MediatorLiveData.java:96)
        at com.connectycube.messenger.vo.NetworkBoundResource$1$1.onChanged(NetworkBoundResource.kt:45)
        at com.connectycube.messenger.vo.NetworkBoundResource$1$1.onChanged(NetworkBoundResource.kt:21)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
I/OpenGLRenderer: Current Surface is null

**Comment by TatankaConCube** [comment]
Hello @choiks14, thank you for your report. Please comment this [line](https://github.com/ConnectyCube/android-messenger-app/blob/master/app/src/main/java/com/connectycube/messenger/ChatDialogActivity.kt#L91) and try again.

**Comment by TatankaConCube** [comment]
We fixed this bug in development branch and will merge to master during next release.

**Comment by TatankaConCube** [comment]
Fixed in version [1.1.0](https://github.com/ConnectyCube/android-messenger-app/releases/tag/1.1.0)
