### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by VNAPNIC** [ConnectyCube/android-messenger-app#22]
Process: com.connectycube.messenger, PID: 5758
    kotlin.KotlinNullPointerException
        at com.connectycube.messenger.LoginActivity$loginTo$$inlined$observe$1.onChanged(LiveData.kt:56)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.connectycube.messenger.vo.NetworkBoundResource.setValue(NetworkBoundResource.kt:56)
        at com.connectycube.messenger.vo.NetworkBoundResource.access$setValue(NetworkBoundResource.kt:21)
        at com.connectycube.messenger.vo.NetworkBoundResource$fetchFromNetwork$2$1$1$1.onChanged(NetworkBoundResource.kt:78)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6578)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by TatankaConCube** [comment]
@VNAPNIC please, strongly follow our [guid ](https://github.com/ConnectyCube/android-messenger-app#how-to-run). In your case you should create users in Admin panel with credential from your .json file

**Comment by VNAPNIC** [comment]
I followed the instructions, but still got the same error

{
  "login1": {"namit123": 181455},
  "login2": {"password2": 12346},
  "login3": {"password3": 12347},
  "login4": {"password4": 12348},
  "login5": {"password5": 12349}
}

**Comment by TatankaConCube** [comment]
Are you sure you created user in admin panel with login="login1", password="namit123", id=181454? 

Now I emulated same situation without created users in admin panel and I got same error. Please recheck it and try again. If you got any error, please copy full log (not stacktrase only) and post it there. To post logs you can use [Gist](https://gist.github.com/)

**Comment by TatankaConCube** [comment]
Fixed in version [1.1.0](https://github.com/ConnectyCube/android-messenger-app/releases/tag/1.1.0). Now you will get an error if app can't load user from json-config.
