### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by ravidhakar** [ConnectyCube/android-messenger-app#29]
kotlin.KotlinNullPointerException
        at com.connectycube.messenger.LoginActivity$loginTo$$inlined$observe$1.onChanged(LiveData.kt:56)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.connectycube.messenger.vo.NetworkBoundResource.setValue(NetworkBoundResource.kt:56)
        at com.connectycube.messenger.vo.NetworkBoundResource.access$setValue(NetworkBoundResource.kt:21)
        at com.connectycube.messenger.vo.NetworkBoundResource$fetchFromNetwork$2$1$1$1.onChanged(NetworkBoundResource.kt:78)
        at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by TatankaConCube** [comment]
Hello @ravidhakar, sorry for longtime answer. Looks like you have same issue with [this issue](https://github.com/ConnectyCube/android-messenger-app/issues/22). Try use solution from it.

**Comment by TatankaConCube** [comment]
Fixed in version [1.1.0](https://github.com/ConnectyCube/android-messenger-app/releases/tag/1.1.0). Now you will get an error if app can't load user from json-config.
