### ISSUE TITLE
Bootstrap method returned null

### ISSUE THREAD

**Issue by vinayappypiellp** [ConnectyCube/android-messenger-app#40]
While using RTCSurgaceView for video chat, facing this issue
Is there a solely sample for video chat only, so that i can get better insights of it.

    java.lang.BootstrapMethodError: Exception from call site #6 bootstrap method
        at org.webrtc.EglRenderer.init(EglRenderer.java:181)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at com.connectycube.videochat.view.RTCSurfaceView.init(RTCSurfaceView.java:46)
        at 
 
 
     com.connectycube.videochat.view.BaseSurfaceViewRenderer.surfaceCreated(BaseSurfaceViewR .     enderer.java:25)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:794)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:181)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:991)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3004)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null

**Comment by TatankaConCube** [comment]
hello @vinayappypiellp, webRTC requires java 8 version for project, add next lines to your module's build.gradle file 

```
android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
} 
```

**Comment by EhsanHasin** [comment]
yes
