### ISSUE TITLE
Crash on send message button click

### ISSUE THREAD

**Issue by jddeep** [ConnectyCube/android-messenger-app#93]
Logs from crashlytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'com.connectycube.users.model.ConnectycubeUser h.d.b.d.d' on a null object reference
       at com.connectycube.chat.ConnectycubeChatService.getUser(ConnectycubeChatService.java:1)
       at com.connectycube.chat.model.ConnectycubeChatDialog.getRecipientId(ConnectycubeChatDialog.java:1)
       at com.mentro.mentro_app.ui.ChatMessageActivity.X(ChatMessageActivity.java:27)
       at com.mentro.mentro_app.ui.ChatMessageActivity.onRequestClick(ChatMessageActivity.java:38)

**Comment by jddeep** [comment]
@TatankaConCube Please look into this

**Comment by jddeep** [comment]
@TatankaConCube any leads please?

**Comment by TatankaConCube** [comment]
I think it related to your previous issues related to the initialization dialog for chatting and adding messages listener. There you had similar issues.

**Comment by jddeep** [comment]
@TatankaConCube Okay then please help me fix that
